<a href="https://colab.research.google.com/github/Unp12/Intern-Slab_1-3/blob/main/Slab_1_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [ ]:
def perform_operations():
    print("Matrix Operations Tool")

    # Input dimensions
    rows = int(input("Enter the number of rows for the matrices: "))
    cols = int(input("Enter the number of columns for the matrices: "))

    print("\nEnter values for Matrix 1:")
    matrix1 = []
    for i in range(rows):
        row = list(map(int, input(f"Row {i + 1}: ").split()))
        matrix1.append(row)
    matrix1 = np.array(matrix1)

    print("\nEnter values for Matrix 2:")
    matrix2 = []
    for i in range(rows):
        row = list(map(int, input(f"Row {i + 1}: ").split()))
        matrix2.append(row)
    matrix2 = np.array(matrix2)

    print("\nMatrix 1:")
    print(matrix1)

    print("\nMatrix 2:")
    print(matrix2)

    # Operations
    print("\nAddition:")
    print(np.add(matrix1, matrix2))

    print("\nSubtraction:")
    print(np.subtract(matrix1, matrix2))

    # Multiplication (if dimensions are valid for dot product)
    try:
        print("\nMultiplication:")
        print(np.dot(matrix1, matrix2))
    except ValueError:
        print("\nMultiplication: Cannot multiply the given matrices with these dimensions.")

    print("\nTranspose of Matrix 1:")
    print(matrix1.T)

    # Determinant (only valid for square matrices)
    if rows == cols:
        print("\nDeterminant of Matrix 1:")
        print(np.linalg.det(matrix1))
    else:
        print("\nDeterminant: Matrix 1 is not square, determinant cannot be calculated.")

# Run the function
perform_operations()

Matrix Operations Tool
Enter the number of rows for the matrices: 3
Enter the number of columns for the matrices: 2

Enter values for Matrix 1:
Row 1: 2
Row 2: 3
Row 3: 4

Enter values for Matrix 2:
Row 1: 2
Row 2: 3
Row 3: 2

Matrix 1:
[[2]
 [3]
 [4]]

Matrix 2:
[[2]
 [3]
 [2]]

Addition:
[[4]
 [6]
 [6]]

Subtraction:
[[0]
 [0]
 [2]]

Multiplication:

Multiplication: Cannot multiply the given matrices with these dimensions.

Transpose of Matrix 1:
[[2 3 4]]

Determinant: Matrix 1 is not square, determinant cannot be calculated.
